package services

import (
	"fmt"
	"testing"
)

var addMailID int64
var mailToken = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhY2Nlc3MiLCJncmFudCI6ImNvZGUiLCJ1c2VySWQiOiJwanMiLCJjbGllbnRJZCI6NDAzLCJyb2xlVXJpcyI6W3siY2xpZW50Um9sZUlkIjoxLCJyb2xlIjoiYWRtaW4iLCJ1cmlJZCI6NzcsInVyaSI6Imh0dHA6Ly9sb2NhbGhvc3QvcnMvYWRkQ2xpZW50U2NvcGUiLCJjbGllbnRJZCI6NDAzfSx7ImNsaWVudFJvbGVJZCI6MSwicm9sZSI6ImFkbWluIiwidXJpSWQiOjMzMCwidXJpIjoiL3JzL2NvbnRlbnQvaGl0cyIsImNsaWVudElkIjo0MDN9LHsiY2xpZW50Um9sZUlkIjoxLCJyb2xlIjoiYWRtaW4iLCJ1cmlJZCI6MjMxLCJ1cmkiOiIvcnMvY3VzdG9tZXIvbGlzdCIsImNsaWVudElkIjo0MDN9LHsiY2xpZW50Um9sZUlkIjoxLCJyb2xlIjoiYWRtaW4iLCJ1cmlJZCI6MTk5LCJ1cmkiOiIvcnMvcm9sZS9kZWxldGUiLCJjbGllbnRJZCI6NDAzfSx7ImNsaWVudFJvbGVJZCI6MSwicm9sZSI6ImFkbWluIiwidXJpSWQiOjI2MSwidXJpIjoiL3JzL29yZGVyL3VwZGF0ZSIsImNsaWVudElkIjo0MDN9LHsiY2xpZW50Um9sZUlkIjoxLCJyb2xlIjoiYWRtaW4iLCJ1cmlJZCI6MjQyLCJ1cmkiOiIvcnMvb3B0aW9ucy9kZWxldGUiLCJjbGllbnRJZCI6NDAzfSx7ImNsaWVudFJvbGVJZCI6MSwicm9sZSI6ImFkbWluIiwidXJpSWQiOjI3MywidXJpIjoiL3JzL2ltYWdlL2FkZCIsImNsaWVudElkIjo0MDN9LHsiY2xpZW50Um9sZUlkIjoxLCJyb2xlIjoiYWRtaW4iLCJ1cmlJZCI6MTY4LCJ1cmkiOiIvcnMvdXNlci9hZGQiLCJjbGllbnRJZCI6NDAzfSx7ImNsaWVudFJvbGVJZCI6MSwicm9sZSI6ImFkbWluIiwidXJpSWQiOjMzMSwidXJpIjoiL3JzL21haWxTZXJ2ZXIvYWRkIiwiY2xpZW50SWQiOjQwM30seyJjbGllbnRSb2xlSWQiOjEsInJvbGUiOiJhZG1pbiIsInVyaUlkIjoyMzIsInVyaSI6Ii9ycy9jdXN0b21lci9kZWxldGUiLCJjbGllbnRJZCI6NDAzfSx7ImNsaWVudFJvbGVJZCI6MSwicm9sZSI6ImFkbWluIiwidXJpSWQiOjIwMCwidXJpIjoiL3JzL3JvbGUvbGlzdCIsImNsaWVudElkIjo0MDN9LHsiY2xpZW50Um9sZUlkIjoxLCJyb2xlIjoiYWRtaW4iLCJ1cmlJZCI6MjY1LCJ1cmkiOiIvcnMvb3JkZXIvZGVsZXRlIiwiY2xpZW50SWQiOjQwM30seyJjbGllbnRSb2xlSWQiOjEsInJvbGUiOiJhZG1pbiIsInVyaUlkIjoyNDMsInVyaSI6Ii9ycy9kZXRhaWxzL2FkZCIsImNsaWVudElkIjo0MDN9LHsiY2xpZW50Um9sZUlkIjoxLCJyb2xlIjoiYWRtaW4iLCJ1cmlJZCI6MjAxLCJ1cmkiOiIvcnMvbWFpbC9zZW5kIiwiY2xpZW50SWQiOjQwM30seyJjbGllbnRSb2xlSWQiOjEsInJvbGUiOiJhZG1pbiIsInVyaUlkIjoxOTIsInVyaSI6Ii9ycy91c2VyL3VwZGF0ZSIsImNsaWVudElkIjo0MDN9LHsiY2xpZW50Um9sZUlkIjoxLCJyb2xlIjoiYWRtaW4iLCJ1cmlJZCI6MzMyLCJ1cmkiOiIvcnMvbWFpbFNlcnZlci91cGRhdGUiLCJjbGllbnRJZCI6NDAzfSx7ImNsaWVudFJvbGVJZCI6MSwicm9sZSI6ImFkbWluIiwidXJpSWQiOjIzMywidXJpIjoiL3JzL3Byb2R1Y3QvYWRkIiwiY2xpZW50SWQiOjQwM30seyJjbGllbnRSb2xlSWQiOjEsInJvbGUiOiJhZG1pbiIsInVyaUlkIjoyNjYsInVyaSI6Ii9ycy9vcmRlci9pdGVtL2FkZCIsImNsaWVudElkIjo0MDN9LHsiY2xpZW50Um9sZUlkIjoxLCJyb2xlIjoiYWRtaW4iLCJ1cmlJZCI6MjQ0LCJ1cmkiOiIvcnMvZGV0YWlscy91cGRhdGUiLCJjbGllbnRJZCI6NDAzfSx7ImNsaWVudFJvbGVJZCI6MSwicm9sZSI6ImFkbWluIiwidXJpSWQiOjIyMywidXJpIjoiL3JzL2FkZHJlc3MvYWRkIiwiY2xpZW50SWQiOjQwM30seyJjbGllbnRSb2xlSWQiOjEsInJvbGUiOiJhZG1pbiIsInVyaUlkIjoxOTMsInVyaSI6Ii9ycy91c2VyL2dldCIsImNsaWVudElkIjo0MDN9LHsiY2xpZW50Um9sZUlkIjoxLCJyb2xlIjoiYWRtaW4iLCJ1cmlJZCI6MzMzLCJ1cmkiOiIvcnMvbWFpbFNlcnZlci9nZXQiLCJjbGllbnRJZCI6NDAzfSx7ImNsaWVudFJvbGVJZCI6MSwicm9sZSI6ImFkbWluIiwidXJpSWQiOjI3NCwidXJpIjoiL3JzL2ltYWdlL3VwZGF0ZSIsImNsaWVudElkIjo0MDN9LHsiY2xpZW50Um9sZUlkIjoxLCJyb2xlIjoiYWRtaW4iLCJ1cmlJZCI6MjY3LCJ1cmkiOiIvcnMvb3JkZXIvaXRlbS91cGRhdGUiLCJjbGllbnRJZCI6NDAzfSx7ImNsaWVudFJvbGVJZCI6MSwicm9sZSI6ImFkbWluIiwidXJpSWQiOjI0OSwidXJpIjoiL3JzL2RldGFpbHMvZGVsZXRlIiwiY2xpZW50SWQiOjQwM30seyJjbGllbnRSb2xlSWQiOjEsInJvbGUiOiJhZG1pbiIsInVyaUlkIjoyNzgsInVyaSI6Ii9ycy9pbWFnZS9kZWxldGUiLCJjbGllbnRJZCI6NDAzfSx7ImNsaWVudFJvbGVJZCI6MSwicm9sZSI6ImFkbWluIiwidXJpSWQiOjIyNCwidXJpIjoiL3JzL2FkZHJlc3MvdXBkYXRlIiwiY2xpZW50SWQiOjQwM30seyJjbGllbnRSb2xlSWQiOjEsInJvbGUiOiJhZG1pbiIsInVyaUlkIjoxOTQsInVyaSI6Ii9ycy91c2VyL2RlbGV0ZSIsImNsaWVudElkIjo0MDN9LHsiY2xpZW50Um9sZUlkIjoxLCJyb2xlIjoiYWRtaW4iLCJ1cmlJZCI6MjY4LCJ1cmkiOiIvcnMvb3JkZXIvaXRlbS9kZWxldGUiLCJjbGllbnRJZCI6NDAzfSx7ImNsaWVudFJvbGVJZCI6MSwicm9sZSI6ImFkbWluIiwidXJpSWQiOjI1NSwidXJpIjoiL3JzL2JhckNvZGUvYWRkIiwiY2xpZW50SWQiOjQwM30seyJjbGllbnRSb2xlSWQiOjEsInJvbGUiOiJhZG1pbiIsInVyaUlkIjoyMzQsInVyaSI6Ii9ycy9wcm9kdWN0L3VwZGF0ZSIsImNsaWVudElkIjo0MDN9LHsiY2xpZW50Um9sZUlkIjoxLCJyb2xlIjoiYWRtaW4iLCJ1cmlJZCI6Mjc5LCJ1cmkiOiIvcnMvY29udGVudC9hZGQiLCJjbGllbnRJZCI6NDAzfSx7ImNsaWVudFJvbGVJZCI6MSwicm9sZSI6ImFkbWluIiwidXJpSWQiOjIyNywidXJpIjoiL3JzL2FkZHJlc3MvZGVsZXRlIiwiY2xpZW50SWQiOjQwM30seyJjbGllbnRSb2xlSWQiOjEsInJvbGUiOiJhZG1pbiIsInVyaUlkIjoxOTUsInVyaSI6Ii9ycy91c2VyL2xpc3QiLCJjbGllbnRJZCI6NDAzfSx7ImNsaWVudFJvbGVJZCI6MSwicm9sZSI6ImFkbWluIiwidXJpSWQiOjIzNiwidXJpIjoiL3JzL3Byb2R1Y3QvZGVsZXRlIiwiY2xpZW50SWQiOjQwM30seyJjbGllbnRSb2xlSWQiOjEsInJvbGUiOiJhZG1pbiIsInVyaUlkIjoyNjksInVyaSI6Ii9ycy9vcmRlci9wYWNrYWdlL2FkZCIsImNsaWVudElkIjo0MDN9LHsiY2xpZW50Um9sZUlkIjoxLCJyb2xlIjoiYWRtaW4iLCJ1cmlJZCI6MjU2LCJ1cmkiOiIvcnMvYmFyQ29kZS91cGRhdGUiLCJjbGllbnRJZCI6NDAzfSx7ImNsaWVudFJvbGVJZCI6MSwicm9sZSI6ImFkbWluIiwidXJpSWQiOjI4MCwidXJpIjoiL3JzL2NvbnRlbnQvdXBkYXRlIiwiY2xpZW50SWQiOjQwM30seyJjbGllbnRSb2xlSWQiOjEsInJvbGUiOiJhZG1pbiIsInVyaUlkIjoyMjgsInVyaSI6Ii9ycy9jdXN0b21lci9hZGQiLCJjbGllbnRJZCI6NDAzfSx7ImNsaWVudFJvbGVJZCI6MSwicm9sZSI6ImFkbWluIiwidXJpSWQiOjE5NiwidXJpIjoiL3JzL3JvbGUvYWRkIiwiY2xpZW50SWQiOjQwM30seyJjbGllbnRSb2xlSWQiOjEsInJvbGUiOiJhZG1pbiIsInVyaUlkIjo2MiwidXJpIjoiaHR0cDovL2xvY2FsaG9zdC9ycy9hZGRDbGllbnQiLCJjbGllbnRJZCI6NDAzfSx7ImNsaWVudFJvbGVJZCI6MSwicm9sZSI6ImFkbWluIiwidXJpSWQiOjIzNywidXJpIjoiL3JzL29wdGlvbnMvYWRkIiwiY2xpZW50SWQiOjQwM30seyJjbGllbnRSb2xlSWQiOjEsInJvbGUiOiJhZG1pbiIsInVyaUlkIjoyNzAsInVyaSI6Ii9ycy9vcmRlci9wYWNrYWdlL3VwZGF0ZSIsImNsaWVudElkIjo0MDN9LHsiY2xpZW50Um9sZUlkIjoxLCJyb2xlIjoiYWRtaW4iLCJ1cmlJZCI6MjU5LCJ1cmkiOiIvcnMvYmFyQ29kZS9kZWxldGUiLCJjbGllbnRJZCI6NDAzfSx7ImNsaWVudFJvbGVJZCI6MSwicm9sZSI6ImFkbWluIiwidXJpSWQiOjYzLCJ1cmkiOiJodHRwOi8vbG9jYWxob3N0L3JzL3VwZGF0ZUNsaWVudCIsImNsaWVudElkIjo0MDN9LHsiY2xpZW50Um9sZUlkIjoxLCJyb2xlIjoiYWRtaW4iLCJ1cmlJZCI6MjgzLCJ1cmkiOiIvcnMvY29udGVudC9kZWxldGUiLCJjbGllbnRJZCI6NDAzfSx7ImNsaWVudFJvbGVJZCI6MSwicm9sZSI6ImFkbWluIiwidXJpSWQiOjIyOSwidXJpIjoiL3JzL2N1c3RvbWVyL3VwZGF0ZSIsImNsaWVudElkIjo0MDN9LHsiY2xpZW50Um9sZUlkIjoxLCJyb2xlIjoiYWRtaW4iLCJ1cmlJZCI6MTk4LCJ1cmkiOiIvcnMvcm9sZS9nZXQiLCJjbGllbnRJZCI6NDAzfSx7ImNsaWVudFJvbGVJZCI6MSwicm9sZSI6ImFkbWluIiwidXJpSWQiOjIzOCwidXJpIjoiL3JzL29wdGlvbnMvdXBkYXRlIiwiY2xpZW50SWQiOjQwM30seyJjbGllbnRSb2xlSWQiOjEsInJvbGUiOiJhZG1pbiIsInVyaUlkIjoyNzIsInVyaSI6Ii9ycy9vcmRlci9wYWNrYWdlL2RlbGV0ZSIsImNsaWVudElkIjo0MDN9LHsiY2xpZW50Um9sZUlkIjoxLCJyb2xlIjoiYWRtaW4iLCJ1cmlJZCI6MjYwLCJ1cmkiOiIvcnMvb3JkZXIvYWRkIiwiY2xpZW50SWQiOjQwM30seyJjbGllbnRSb2xlSWQiOjIsInJvbGUiOiJ1c2VyIiwidXJpSWQiOjIzMCwidXJpIjoiL3JzL2N1c3RvbWVyL2dldCIsImNsaWVudElkIjo0MDN9LHsiY2xpZW50Um9sZUlkIjoyLCJyb2xlIjoidXNlciIsInVyaUlkIjoyNzEsInVyaSI6Ii9ycy9vcmRlci9wYWNrYWdlL2dldCIsImNsaWVudElkIjo0MDN9LHsiY2xpZW50Um9sZUlkIjoyLCJyb2xlIjoidXNlciIsInVyaUlkIjoyMzEsInVyaSI6Ii9ycy9jdXN0b21lci9saXN0IiwiY2xpZW50SWQiOjQwM30seyJjbGllbnRSb2xlSWQiOjIsInJvbGUiOiJ1c2VyIiwidXJpSWQiOjI3NSwidXJpIjoiL3JzL2ltYWdlL2RldGFpbHMiLCJjbGllbnRJZCI6NDAzfSx7ImNsaWVudFJvbGVJZCI6Miwicm9sZSI6InVzZXIiLCJ1cmlJZCI6MjQ3LCJ1cmkiOiIvcnMvZGV0YWlscy9nZXRCeVNrdSIsImNsaWVudElkIjo0MDN9LHsiY2xpZW50Um9sZUlkIjoyLCJyb2xlIjoidXNlciIsInVyaUlkIjoyMzUsInVyaSI6Ii9ycy9wcm9kdWN0L2dldCIsImNsaWVudElkIjo0MDN9LHsiY2xpZW50Um9sZUlkIjoyLCJyb2xlIjoidXNlciIsInVyaUlkIjoyNDgsInVyaSI6Ii9ycy9kZXRhaWxzL2dldEJ5QmFyQ29kZSIsImNsaWVudElkIjo0MDN9LHsiY2xpZW50Um9sZUlkIjoyLCJyb2xlIjoidXNlciIsInVyaUlkIjoyNzYsInVyaSI6Ii9ycy9pbWFnZS9wYWdlL2NvdW50IiwiY2xpZW50SWQiOjQwM30seyJjbGllbnRSb2xlSWQiOjIsInJvbGUiOiJ1c2VyIiwidXJpSWQiOjIzOSwidXJpIjoiL3JzL29wdGlvbnMvZ2V0IiwiY2xpZW50SWQiOjQwM30seyJjbGllbnRSb2xlSWQiOjIsInJvbGUiOiJ1c2VyIiwidXJpSWQiOjI1NywidXJpIjoiL3JzL2JhckNvZGUvZ2V0IiwiY2xpZW50SWQiOjQwM30seyJjbGllbnRSb2xlSWQiOjIsInJvbGUiOiJ1c2VyIiwidXJpSWQiOjI3NywidXJpIjoiL3JzL2ltYWdlL2xpc3QiLCJjbGllbnRJZCI6NDAzfSx7ImNsaWVudFJvbGVJZCI6Miwicm9sZSI6InVzZXIiLCJ1cmlJZCI6MjQwLCJ1cmkiOiIvcnMvb3B0aW9ucy9nZXRCeURldGFpbHMiLCJjbGllbnRJZCI6NDAzfSx7ImNsaWVudFJvbGVJZCI6Miwicm9sZSI6InVzZXIiLCJ1cmlJZCI6NjgsInVyaSI6Imh0dHA6Ly9sb2NhbGhvc3QvcnMvZGVsZXRlQ2xpZW50QWxsb3dlZFVyaSIsImNsaWVudElkIjo0MDN9LHsiY2xpZW50Um9sZUlkIjoyLCJyb2xlIjoidXNlciIsInVyaUlkIjoyNTgsInVyaSI6Ii9ycy9iYXJDb2RlL2dldEJ5RGV0YWlscyIsImNsaWVudElkIjo0MDN9LHsiY2xpZW50Um9sZUlkIjoyLCJyb2xlIjoidXNlciIsInVyaUlkIjoyODEsInVyaSI6Ii9ycy9jb250ZW50L2dldCIsImNsaWVudElkIjo0MDN9LHsiY2xpZW50Um9sZUlkIjoyLCJyb2xlIjoidXNlciIsInVyaUlkIjoyNDEsInVyaSI6Ii9ycy9vcHRpb25zL3NlYXJjaEJ5T3B0aW9uIiwiY2xpZW50SWQiOjQwM30seyJjbGllbnRSb2xlSWQiOjIsInJvbGUiOiJ1c2VyIiwidXJpSWQiOjgwLCJ1cmkiOiJodHRwOi8vbG9jYWxob3N0L3JzL2FkZENsaWVudFJvbGVVcmkiLCJjbGllbnRJZCI6NDAzfSx7ImNsaWVudFJvbGVJZCI6Miwicm9sZSI6InVzZXIiLCJ1cmlJZCI6MjgyLCJ1cmkiOiIvcnMvY29udGVudC9saXN0IiwiY2xpZW50SWQiOjQwM30seyJjbGllbnRSb2xlSWQiOjIsInJvbGUiOiJ1c2VyIiwidXJpSWQiOjI2MiwidXJpIjoiL3JzL29yZGVyL2dldCIsImNsaWVudElkIjo0MDN9LHsiY2xpZW50Um9sZUlkIjoyLCJyb2xlIjoidXNlciIsInVyaUlkIjoyNDUsInVyaSI6Ii9ycy9kZXRhaWxzL2dldCIsImNsaWVudElkIjo0MDN9LHsiY2xpZW50Um9sZUlkIjoyLCJyb2xlIjoidXNlciIsInVyaUlkIjoyMjUsInVyaSI6Ii9ycy9hZGRyZXNzL2dldCIsImNsaWVudElkIjo0MDN9LHsiY2xpZW50Um9sZUlkIjoyLCJyb2xlIjoidXNlciIsInVyaUlkIjoyNjMsInVyaSI6Ii9ycy9vcmRlci9saXN0IiwiY2xpZW50SWQiOjQwM30seyJjbGllbnRSb2xlSWQiOjIsInJvbGUiOiJ1c2VyIiwidXJpSWQiOjIyNiwidXJpIjoiL3JzL2FkZHJlc3MvbGlzdCIsImNsaWVudElkIjo0MDN9LHsiY2xpZW50Um9sZUlkIjoyLCJyb2xlIjoidXNlciIsInVyaUlkIjoyNDYsInVyaSI6Ii9ycy9kZXRhaWxzL2dldEJ5UHJvZHVjdCIsImNsaWVudElkIjo0MDN9LHsiY2xpZW50Um9sZUlkIjoyLCJyb2xlIjoidXNlciIsInVyaUlkIjoyNjQsInVyaSI6Ii9ycy9vcmRlci9jdXN0b21lci9saXN0IiwiY2xpZW50SWQiOjQwM31dLCJzY29wZUxpc3QiOlsicmVhZCIsIndyaXRlIl0sImV4cGlyZXNJbiI6MzYwMCwiaWF0IjoxNTA0Mzk5OTU5LCJ0b2tlblR5cGUiOiJhY2Nlc3MiLCJleHAiOjE1MDQ0MDM1NTksImlzcyI6IlVsYm9yYSBPYXV0aDIgU2VydmVyIn0.LmCvePQ5b-fa9eMZi5mC8aWu_km0LTkH9B_XGGnzO58"

func TestMailServerService_AddMailServer(t *testing.T) {
	var m MailServerService
	m.ClientID = "403"
	m.Host = "http://localhost:3002"
	m.Token = mailToken
	var ms MailServer
	ms.MailServer = "mail.some.com"
	ms.SecureConnection = true
	ms.Port = 465
	ms.Debug = false
	ms.Username = "ken"
	ms.Password = "ken"
	ms.FromAddress = "ken@ken.com"
	ms.ClientID = 403
	res := m.AddMailServer(&ms)
	fmt.Print("mail server add res: ")
	fmt.Println(res)
	addMailID = res.ID
	if res.Success != true {
		t.Fail()
	}
}

func TestMailServerService_UpdateMailServer(t *testing.T) {
	var m MailServerService
	m.ClientID = "403"
	m.Host = "http://localhost:3002"
	m.Token = mailToken
	var ms MailServer
	ms.ID = addMailID
	ms.MailServer = "mail.some.com"
	ms.SecureConnection = true
	ms.Port = 465
	ms.Debug = true
	ms.Username = "ken"
	ms.Password = "ken"
	ms.FromAddress = "ken1@ken.com"
	ms.ClientID = 403
	res := m.UpdateMailServer(&ms)
	fmt.Print("mail server add res: ")
	fmt.Println(res)
	addMailID = res.ID
	if res.Success != true {
		t.Fail()
	}
}

func TestContentService_GetMailServer(t *testing.T) {
	var m MailServerService
	m.ClientID = "403"
	m.Host = "http://localhost:3002"
	m.Token = mailToken
	res := m.GetMailServer()
	fmt.Print("res server get: ")
	fmt.Println(res)
	if res.Success != true {
		t.Fail()
	}
}

// func TestMailServerService_SendMail(t *testing.T) {
// 	var m MailServerService
// 	m.ClientID = "403"
// 	m.Host = "http://localhost:3002"
// 	m.Token = token
// 	var ms MailMessage
// 	ms.FromEmail
// 	res := m.SendMail(&ms)
// 	fmt.Print("send mail res: ")
// 	fmt.Println(res)
// 	addMailID = res.ID
// 	if res.Success != true {
// 		t.Fail()
// 	}
// }
