package services

import (
	"fmt"
	"strconv"
	"testing"
)

var tempAddID int64
var tempAddID2 int64
var tempToken = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhY2Nlc3MiLCJncmFudCI6ImNvZGUiLCJ1c2VySWQiOiJwanMiLCJjbGllbnRJZCI6NDAzLCJyb2xlVXJpcyI6W3siY2xpZW50Um9sZUlkIjoxLCJyb2xlIjoiYWRtaW4iLCJ1cmlJZCI6MjY3LCJ1cmkiOiIvcnMvb3JkZXIvaXRlbS91cGRhdGUiLCJjbGllbnRJZCI6NDAzfSx7ImNsaWVudFJvbGVJZCI6MSwicm9sZSI6ImFkbWluIiwidXJpSWQiOjI0OSwidXJpIjoiL3JzL2RldGFpbHMvZGVsZXRlIiwiY2xpZW50SWQiOjQwM30seyJjbGllbnRSb2xlSWQiOjEsInJvbGUiOiJhZG1pbiIsInVyaUlkIjozMzQsInVyaSI6Ii9ycy90ZW1wbGF0ZS9hZGQiLCJjbGllbnRJZCI6NDAzfSx7ImNsaWVudFJvbGVJZCI6MSwicm9sZSI6ImFkbWluIiwidXJpSWQiOjI3OCwidXJpIjoiL3JzL2ltYWdlL2RlbGV0ZSIsImNsaWVudElkIjo0MDN9LHsiY2xpZW50Um9sZUlkIjoxLCJyb2xlIjoiYWRtaW4iLCJ1cmlJZCI6MjI0LCJ1cmkiOiIvcnMvYWRkcmVzcy91cGRhdGUiLCJjbGllbnRJZCI6NDAzfSx7ImNsaWVudFJvbGVJZCI6MSwicm9sZSI6ImFkbWluIiwidXJpSWQiOjE5NCwidXJpIjoiL3JzL3VzZXIvZGVsZXRlIiwiY2xpZW50SWQiOjQwM30seyJjbGllbnRSb2xlSWQiOjEsInJvbGUiOiJhZG1pbiIsInVyaUlkIjoyNTUsInVyaSI6Ii9ycy9iYXJDb2RlL2FkZCIsImNsaWVudElkIjo0MDN9LHsiY2xpZW50Um9sZUlkIjoxLCJyb2xlIjoiYWRtaW4iLCJ1cmlJZCI6MjM0LCJ1cmkiOiIvcnMvcHJvZHVjdC91cGRhdGUiLCJjbGllbnRJZCI6NDAzfSx7ImNsaWVudFJvbGVJZCI6MSwicm9sZSI6ImFkbWluIiwidXJpSWQiOjI2OCwidXJpIjoiL3JzL29yZGVyL2l0ZW0vZGVsZXRlIiwiY2xpZW50SWQiOjQwM30seyJjbGllbnRSb2xlSWQiOjEsInJvbGUiOiJhZG1pbiIsInVyaUlkIjozMzUsInVyaSI6Ii9ycy90ZW1wbGF0ZS91cGRhdGUiLCJjbGllbnRJZCI6NDAzfSx7ImNsaWVudFJvbGVJZCI6MSwicm9sZSI6ImFkbWluIiwidXJpSWQiOjI3OSwidXJpIjoiL3JzL2NvbnRlbnQvYWRkIiwiY2xpZW50SWQiOjQwM30seyJjbGllbnRSb2xlSWQiOjEsInJvbGUiOiJhZG1pbiIsInVyaUlkIjoyMjcsInVyaSI6Ii9ycy9hZGRyZXNzL2RlbGV0ZSIsImNsaWVudElkIjo0MDN9LHsiY2xpZW50Um9sZUlkIjoxLCJyb2xlIjoiYWRtaW4iLCJ1cmlJZCI6MTk1LCJ1cmkiOiIvcnMvdXNlci9saXN0IiwiY2xpZW50SWQiOjQwM30seyJjbGllbnRSb2xlSWQiOjEsInJvbGUiOiJhZG1pbiIsInVyaUlkIjoyNTYsInVyaSI6Ii9ycy9iYXJDb2RlL3VwZGF0ZSIsImNsaWVudElkIjo0MDN9LHsiY2xpZW50Um9sZUlkIjoxLCJyb2xlIjoiYWRtaW4iLCJ1cmlJZCI6MjM2LCJ1cmkiOiIvcnMvcHJvZHVjdC9kZWxldGUiLCJjbGllbnRJZCI6NDAzfSx7ImNsaWVudFJvbGVJZCI6MSwicm9sZSI6ImFkbWluIiwidXJpSWQiOjI2OSwidXJpIjoiL3JzL29yZGVyL3BhY2thZ2UvYWRkIiwiY2xpZW50SWQiOjQwM30seyJjbGllbnRSb2xlSWQiOjEsInJvbGUiOiJhZG1pbiIsInVyaUlkIjoxOTYsInVyaSI6Ii9ycy9yb2xlL2FkZCIsImNsaWVudElkIjo0MDN9LHsiY2xpZW50Um9sZUlkIjoxLCJyb2xlIjoiYWRtaW4iLCJ1cmlJZCI6NjIsInVyaSI6Imh0dHA6Ly9sb2NhbGhvc3QvcnMvYWRkQ2xpZW50IiwiY2xpZW50SWQiOjQwM30seyJjbGllbnRSb2xlSWQiOjEsInJvbGUiOiJhZG1pbiIsInVyaUlkIjoyODAsInVyaSI6Ii9ycy9jb250ZW50L3VwZGF0ZSIsImNsaWVudElkIjo0MDN9LHsiY2xpZW50Um9sZUlkIjoxLCJyb2xlIjoiYWRtaW4iLCJ1cmlJZCI6MjI4LCJ1cmkiOiIvcnMvY3VzdG9tZXIvYWRkIiwiY2xpZW50SWQiOjQwM30seyJjbGllbnRSb2xlSWQiOjEsInJvbGUiOiJhZG1pbiIsInVyaUlkIjoyNTksInVyaSI6Ii9ycy9iYXJDb2RlL2RlbGV0ZSIsImNsaWVudElkIjo0MDN9LHsiY2xpZW50Um9sZUlkIjoxLCJyb2xlIjoiYWRtaW4iLCJ1cmlJZCI6MjM3LCJ1cmkiOiIvcnMvb3B0aW9ucy9hZGQiLCJjbGllbnRJZCI6NDAzfSx7ImNsaWVudFJvbGVJZCI6MSwicm9sZSI6ImFkbWluIiwidXJpSWQiOjI3MCwidXJpIjoiL3JzL29yZGVyL3BhY2thZ2UvdXBkYXRlIiwiY2xpZW50SWQiOjQwM30seyJjbGllbnRSb2xlSWQiOjEsInJvbGUiOiJhZG1pbiIsInVyaUlkIjoxOTgsInVyaSI6Ii9ycy9yb2xlL2dldCIsImNsaWVudElkIjo0MDN9LHsiY2xpZW50Um9sZUlkIjoxLCJyb2xlIjoiYWRtaW4iLCJ1cmlJZCI6NjMsInVyaSI6Imh0dHA6Ly9sb2NhbGhvc3QvcnMvdXBkYXRlQ2xpZW50IiwiY2xpZW50SWQiOjQwM30seyJjbGllbnRSb2xlSWQiOjEsInJvbGUiOiJhZG1pbiIsInVyaUlkIjoyODMsInVyaSI6Ii9ycy9jb250ZW50L2RlbGV0ZSIsImNsaWVudElkIjo0MDN9LHsiY2xpZW50Um9sZUlkIjoxLCJyb2xlIjoiYWRtaW4iLCJ1cmlJZCI6MjI5LCJ1cmkiOiIvcnMvY3VzdG9tZXIvdXBkYXRlIiwiY2xpZW50SWQiOjQwM30seyJjbGllbnRSb2xlSWQiOjEsInJvbGUiOiJhZG1pbiIsInVyaUlkIjoyNzIsInVyaSI6Ii9ycy9vcmRlci9wYWNrYWdlL2RlbGV0ZSIsImNsaWVudElkIjo0MDN9LHsiY2xpZW50Um9sZUlkIjoxLCJyb2xlIjoiYWRtaW4iLCJ1cmlJZCI6MjYwLCJ1cmkiOiIvcnMvb3JkZXIvYWRkIiwiY2xpZW50SWQiOjQwM30seyJjbGllbnRSb2xlSWQiOjEsInJvbGUiOiJhZG1pbiIsInVyaUlkIjoyMzgsInVyaSI6Ii9ycy9vcHRpb25zL3VwZGF0ZSIsImNsaWVudElkIjo0MDN9LHsiY2xpZW50Um9sZUlkIjoxLCJyb2xlIjoiYWRtaW4iLCJ1cmlJZCI6MTk5LCJ1cmkiOiIvcnMvcm9sZS9kZWxldGUiLCJjbGllbnRJZCI6NDAzfSx7ImNsaWVudFJvbGVJZCI6MSwicm9sZSI6ImFkbWluIiwidXJpSWQiOjc3LCJ1cmkiOiJodHRwOi8vbG9jYWxob3N0L3JzL2FkZENsaWVudFNjb3BlIiwiY2xpZW50SWQiOjQwM30seyJjbGllbnRSb2xlSWQiOjEsInJvbGUiOiJhZG1pbiIsInVyaUlkIjozMzAsInVyaSI6Ii9ycy9jb250ZW50L2hpdHMiLCJjbGllbnRJZCI6NDAzfSx7ImNsaWVudFJvbGVJZCI6MSwicm9sZSI6ImFkbWluIiwidXJpSWQiOjIzMSwidXJpIjoiL3JzL2N1c3RvbWVyL2xpc3QiLCJjbGllbnRJZCI6NDAzfSx7ImNsaWVudFJvbGVJZCI6MSwicm9sZSI6ImFkbWluIiwidXJpSWQiOjI3MywidXJpIjoiL3JzL2ltYWdlL2FkZCIsImNsaWVudElkIjo0MDN9LHsiY2xpZW50Um9sZUlkIjoxLCJyb2xlIjoiYWRtaW4iLCJ1cmlJZCI6MjYxLCJ1cmkiOiIvcnMvb3JkZXIvdXBkYXRlIiwiY2xpZW50SWQiOjQwM30seyJjbGllbnRSb2xlSWQiOjEsInJvbGUiOiJhZG1pbiIsInVyaUlkIjoyNDIsInVyaSI6Ii9ycy9vcHRpb25zL2RlbGV0ZSIsImNsaWVudElkIjo0MDN9LHsiY2xpZW50Um9sZUlkIjoxLCJyb2xlIjoiYWRtaW4iLCJ1cmlJZCI6MjMyLCJ1cmkiOiIvcnMvY3VzdG9tZXIvZGVsZXRlIiwiY2xpZW50SWQiOjQwM30seyJjbGllbnRSb2xlSWQiOjEsInJvbGUiOiJhZG1pbiIsInVyaUlkIjoyMDAsInVyaSI6Ii9ycy9yb2xlL2xpc3QiLCJjbGllbnRJZCI6NDAzfSx7ImNsaWVudFJvbGVJZCI6MSwicm9sZSI6ImFkbWluIiwidXJpSWQiOjE2OCwidXJpIjoiL3JzL3VzZXIvYWRkIiwiY2xpZW50SWQiOjQwM30seyJjbGllbnRSb2xlSWQiOjEsInJvbGUiOiJhZG1pbiIsInVyaUlkIjozMzEsInVyaSI6Ii9ycy9tYWlsU2VydmVyL2FkZCIsImNsaWVudElkIjo0MDN9LHsiY2xpZW50Um9sZUlkIjoxLCJyb2xlIjoiYWRtaW4iLCJ1cmlJZCI6MjY1LCJ1cmkiOiIvcnMvb3JkZXIvZGVsZXRlIiwiY2xpZW50SWQiOjQwM30seyJjbGllbnRSb2xlSWQiOjEsInJvbGUiOiJhZG1pbiIsInVyaUlkIjoyNDMsInVyaSI6Ii9ycy9kZXRhaWxzL2FkZCIsImNsaWVudElkIjo0MDN9LHsiY2xpZW50Um9sZUlkIjoxLCJyb2xlIjoiYWRtaW4iLCJ1cmlJZCI6MjMzLCJ1cmkiOiIvcnMvcHJvZHVjdC9hZGQiLCJjbGllbnRJZCI6NDAzfSx7ImNsaWVudFJvbGVJZCI6MSwicm9sZSI6ImFkbWluIiwidXJpSWQiOjIwMSwidXJpIjoiL3JzL21haWwvc2VuZCIsImNsaWVudElkIjo0MDN9LHsiY2xpZW50Um9sZUlkIjoxLCJyb2xlIjoiYWRtaW4iLCJ1cmlJZCI6MTkyLCJ1cmkiOiIvcnMvdXNlci91cGRhdGUiLCJjbGllbnRJZCI6NDAzfSx7ImNsaWVudFJvbGVJZCI6MSwicm9sZSI6ImFkbWluIiwidXJpSWQiOjMzMiwidXJpIjoiL3JzL21haWxTZXJ2ZXIvdXBkYXRlIiwiY2xpZW50SWQiOjQwM30seyJjbGllbnRSb2xlSWQiOjEsInJvbGUiOiJhZG1pbiIsInVyaUlkIjoyNjYsInVyaSI6Ii9ycy9vcmRlci9pdGVtL2FkZCIsImNsaWVudElkIjo0MDN9LHsiY2xpZW50Um9sZUlkIjoxLCJyb2xlIjoiYWRtaW4iLCJ1cmlJZCI6MjQ0LCJ1cmkiOiIvcnMvZGV0YWlscy91cGRhdGUiLCJjbGllbnRJZCI6NDAzfSx7ImNsaWVudFJvbGVJZCI6MSwicm9sZSI6ImFkbWluIiwidXJpSWQiOjI3NCwidXJpIjoiL3JzL2ltYWdlL3VwZGF0ZSIsImNsaWVudElkIjo0MDN9LHsiY2xpZW50Um9sZUlkIjoxLCJyb2xlIjoiYWRtaW4iLCJ1cmlJZCI6MjIzLCJ1cmkiOiIvcnMvYWRkcmVzcy9hZGQiLCJjbGllbnRJZCI6NDAzfSx7ImNsaWVudFJvbGVJZCI6MSwicm9sZSI6ImFkbWluIiwidXJpSWQiOjE5MywidXJpIjoiL3JzL3VzZXIvZ2V0IiwiY2xpZW50SWQiOjQwM30seyJjbGllbnRSb2xlSWQiOjEsInJvbGUiOiJhZG1pbiIsInVyaUlkIjozMzMsInVyaSI6Ii9ycy9tYWlsU2VydmVyL2dldCIsImNsaWVudElkIjo0MDN9LHsiY2xpZW50Um9sZUlkIjoyLCJyb2xlIjoidXNlciIsInVyaUlkIjoyNzUsInVyaSI6Ii9ycy9pbWFnZS9kZXRhaWxzIiwiY2xpZW50SWQiOjQwM30seyJjbGllbnRSb2xlSWQiOjIsInJvbGUiOiJ1c2VyIiwidXJpSWQiOjI0NywidXJpIjoiL3JzL2RldGFpbHMvZ2V0QnlTa3UiLCJjbGllbnRJZCI6NDAzfSx7ImNsaWVudFJvbGVJZCI6Miwicm9sZSI6InVzZXIiLCJ1cmlJZCI6MjM1LCJ1cmkiOiIvcnMvcHJvZHVjdC9nZXQiLCJjbGllbnRJZCI6NDAzfSx7ImNsaWVudFJvbGVJZCI6Miwicm9sZSI6InVzZXIiLCJ1cmlJZCI6Mjc2LCJ1cmkiOiIvcnMvaW1hZ2UvcGFnZS9jb3VudCIsImNsaWVudElkIjo0MDN9LHsiY2xpZW50Um9sZUlkIjoyLCJyb2xlIjoidXNlciIsInVyaUlkIjoyNDgsInVyaSI6Ii9ycy9kZXRhaWxzL2dldEJ5QmFyQ29kZSIsImNsaWVudElkIjo0MDN9LHsiY2xpZW50Um9sZUlkIjoyLCJyb2xlIjoidXNlciIsInVyaUlkIjoyMzksInVyaSI6Ii9ycy9vcHRpb25zL2dldCIsImNsaWVudElkIjo0MDN9LHsiY2xpZW50Um9sZUlkIjoyLCJyb2xlIjoidXNlciIsInVyaUlkIjoyNzcsInVyaSI6Ii9ycy9pbWFnZS9saXN0IiwiY2xpZW50SWQiOjQwM30seyJjbGllbnRSb2xlSWQiOjIsInJvbGUiOiJ1c2VyIiwidXJpSWQiOjI1NywidXJpIjoiL3JzL2JhckNvZGUvZ2V0IiwiY2xpZW50SWQiOjQwM30seyJjbGllbnRSb2xlSWQiOjIsInJvbGUiOiJ1c2VyIiwidXJpSWQiOjI0MCwidXJpIjoiL3JzL29wdGlvbnMvZ2V0QnlEZXRhaWxzIiwiY2xpZW50SWQiOjQwM30seyJjbGllbnRSb2xlSWQiOjIsInJvbGUiOiJ1c2VyIiwidXJpSWQiOjY4LCJ1cmkiOiJodHRwOi8vbG9jYWxob3N0L3JzL2RlbGV0ZUNsaWVudEFsbG93ZWRVcmkiLCJjbGllbnRJZCI6NDAzfSx7ImNsaWVudFJvbGVJZCI6Miwicm9sZSI6InVzZXIiLCJ1cmlJZCI6MjgxLCJ1cmkiOiIvcnMvY29udGVudC9nZXQiLCJjbGllbnRJZCI6NDAzfSx7ImNsaWVudFJvbGVJZCI6Miwicm9sZSI6InVzZXIiLCJ1cmlJZCI6MjU4LCJ1cmkiOiIvcnMvYmFyQ29kZS9nZXRCeURldGFpbHMiLCJjbGllbnRJZCI6NDAzfSx7ImNsaWVudFJvbGVJZCI6Miwicm9sZSI6InVzZXIiLCJ1cmlJZCI6MjQxLCJ1cmkiOiIvcnMvb3B0aW9ucy9zZWFyY2hCeU9wdGlvbiIsImNsaWVudElkIjo0MDN9LHsiY2xpZW50Um9sZUlkIjoyLCJyb2xlIjoidXNlciIsInVyaUlkIjo4MCwidXJpIjoiaHR0cDovL2xvY2FsaG9zdC9ycy9hZGRDbGllbnRSb2xlVXJpIiwiY2xpZW50SWQiOjQwM30seyJjbGllbnRSb2xlSWQiOjIsInJvbGUiOiJ1c2VyIiwidXJpSWQiOjI4MiwidXJpIjoiL3JzL2NvbnRlbnQvbGlzdCIsImNsaWVudElkIjo0MDN9LHsiY2xpZW50Um9sZUlkIjoyLCJyb2xlIjoidXNlciIsInVyaUlkIjoyNjIsInVyaSI6Ii9ycy9vcmRlci9nZXQiLCJjbGllbnRJZCI6NDAzfSx7ImNsaWVudFJvbGVJZCI6Miwicm9sZSI6InVzZXIiLCJ1cmlJZCI6MjI1LCJ1cmkiOiIvcnMvYWRkcmVzcy9nZXQiLCJjbGllbnRJZCI6NDAzfSx7ImNsaWVudFJvbGVJZCI6Miwicm9sZSI6InVzZXIiLCJ1cmlJZCI6MjYzLCJ1cmkiOiIvcnMvb3JkZXIvbGlzdCIsImNsaWVudElkIjo0MDN9LHsiY2xpZW50Um9sZUlkIjoyLCJyb2xlIjoidXNlciIsInVyaUlkIjoyMjYsInVyaSI6Ii9ycy9hZGRyZXNzL2xpc3QiLCJjbGllbnRJZCI6NDAzfSx7ImNsaWVudFJvbGVJZCI6Miwicm9sZSI6InVzZXIiLCJ1cmlJZCI6MjQ1LCJ1cmkiOiIvcnMvZGV0YWlscy9nZXQiLCJjbGllbnRJZCI6NDAzfSx7ImNsaWVudFJvbGVJZCI6Miwicm9sZSI6InVzZXIiLCJ1cmlJZCI6MjY0LCJ1cmkiOiIvcnMvb3JkZXIvY3VzdG9tZXIvbGlzdCIsImNsaWVudElkIjo0MDN9LHsiY2xpZW50Um9sZUlkIjoyLCJyb2xlIjoidXNlciIsInVyaUlkIjoyMzAsInVyaSI6Ii9ycy9jdXN0b21lci9nZXQiLCJjbGllbnRJZCI6NDAzfSx7ImNsaWVudFJvbGVJZCI6Miwicm9sZSI6InVzZXIiLCJ1cmlJZCI6MjcxLCJ1cmkiOiIvcnMvb3JkZXIvcGFja2FnZS9nZXQiLCJjbGllbnRJZCI6NDAzfSx7ImNsaWVudFJvbGVJZCI6Miwicm9sZSI6InVzZXIiLCJ1cmlJZCI6MjQ2LCJ1cmkiOiIvcnMvZGV0YWlscy9nZXRCeVByb2R1Y3QiLCJjbGllbnRJZCI6NDAzfSx7ImNsaWVudFJvbGVJZCI6Miwicm9sZSI6InVzZXIiLCJ1cmlJZCI6MjMxLCJ1cmkiOiIvcnMvY3VzdG9tZXIvbGlzdCIsImNsaWVudElkIjo0MDN9XSwic2NvcGVMaXN0IjpbInJlYWQiLCJ3cml0ZSJdLCJleHBpcmVzSW4iOjM2MDAsImlhdCI6MTUwNDU2MjcwMCwidG9rZW5UeXBlIjoiYWNjZXNzIiwiZXhwIjoxNTA0NTY2MzAwLCJpc3MiOiJVbGJvcmEgT2F1dGgyIFNlcnZlciJ9.7l70NMV57ketO8lCg2fn23_6X3ck4F1_aZnJ_FEmPNM"

func TestTemplateService_AddTemplate(t *testing.T) {
	var ts TemplateService
	ts.ClientID = "403"
	ts.Host = "http://localhost:3009"
	ts.Token = tempToken
	var tm Template
	tm.Name = "test temp1"
	tm.Application = "cms"
	tm.ClientID = 7
	res := ts.AddTemplate(&tm)
	fmt.Print("res: ")
	fmt.Println(res)
	tempAddID = res.ID
	if res.Success != true {
		t.Fail()
	}
}

func TestTemplateService_UpdateTemplate(t *testing.T) {
	var ts TemplateService
	ts.ClientID = "403"
	ts.Host = "http://localhost:3009"
	ts.Token = tempToken
	var tm Template
	tm.ID = tempAddID
	tm.Application = "cms"
	res := ts.UpdateTemplate(&tm)
	fmt.Print("res: ")
	fmt.Println(res)
	if res.Success != true {
		t.Fail()
	}
}

func TestTemplateService_GetTemplate(t *testing.T) {
	var ts TemplateService
	ts.Host = "http://localhost:3009"
	res := ts.GetTemplate("cms", "403")
	fmt.Print("res: ")
	fmt.Println(res)
	if res.Active != true {
		t.Fail()
	}
}

func TestTemplateService_GetTemplateList(t *testing.T) {
	var ts TemplateService
	ts.Host = "http://localhost:3009"
	res := ts.GetTemplateList("cms", "403")
	fmt.Print("res list: ")
	fmt.Println(res)
	fmt.Print("len: ")
	fmt.Println(len(*res))
	if res == nil || len(*res) == 0 {
		t.Fail()
	}
}

func TestTemplateService_DeleteTemplate(t *testing.T) {
	var ts TemplateService
	ts.ClientID = "403"
	ts.Host = "http://localhost:3009"
	ts.Token = tempToken
	res := ts.DeleteTemplate(strconv.FormatInt(tempAddID, 10))
	fmt.Print("res deleted: ")
	fmt.Println(res)
	if res.Success != true {
		t.Fail()
	}
}
